#!/bin/sh
#
# vzsandbox-lbapi Starts/stop the "vzsandbox-lbapi" daemon
#
# chkconfig:   345 97 19
# description: Starts the vzsandbox-lbapi daemon which load balances
#    build requests between vzsandbox-api hypervisors

### BEGIN INIT INFO
# Provides: vzsandbox-lbapi
# Required-Start: $local_fs $net
# Required-Stop: $local_fs $net
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
# Short-Description: vzsandbox-lbapi Starts/stop the "vzsandbox-lbapi" daemon
# Description:      Starts the vzsandbox-lbapi daemon which load balances
#    build requests between vzsandbox-api hypervisors
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec=/usr/local/bin/vzsandbox-lbapi-daemon.sh
prog="vzsandbox-lbapi.py"
config=/etc/sysconfig/vzsandbox-lbapi

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon $exec $OPTS
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
